/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;


/**
 *
 * @author ABHISHEK
 */
public class Cuisines extends javax.swing.JFrame {
   Connection conn;
    PreparedStatement pst;
    PreparedStatement pst1;
    ResultSet rs;
   
    
   
    
    
    public Cuisines() {
        initComponents();
         conn = connect.getConnection();
    }
     public void close(){
    
    WindowEvent w=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ns3 = new javax.swing.JRadioButton();
        vs1 = new javax.swing.JRadioButton();
        vs2 = new javax.swing.JRadioButton();
        vs3 = new javax.swing.JRadioButton();
        vs4 = new javax.swing.JRadioButton();
        ns1 = new javax.swing.JRadioButton();
        ns2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        d2 = new javax.swing.JRadioButton();
        d1 = new javax.swing.JRadioButton();
        d3 = new javax.swing.JRadioButton();
        d4 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vm1 = new javax.swing.JRadioButton();
        vm2 = new javax.swing.JRadioButton();
        vm3 = new javax.swing.JRadioButton();
        vm4 = new javax.swing.JRadioButton();
        nm1 = new javax.swing.JRadioButton();
        nm2 = new javax.swing.JRadioButton();
        nm3 = new javax.swing.JRadioButton();
        reset = new javax.swing.JButton();
        add = new javax.swing.JButton();
        reserve = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 650));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setText("Cuisines");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 240, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 30, 250, 80);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        back.setText("HOME");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(960, 520, 170, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Starters");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 10, 110, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 280, 10);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Non-Veg");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 60, 80, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Veg");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 70, 40, 20);

        ns3.setText("Fish Finger");
        jPanel2.add(ns3);
        ns3.setBounds(140, 160, 90, 23);

        vs1.setText("PANEER PAKODA");
        vs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vs1ActionPerformed(evt);
            }
        });
        jPanel2.add(vs1);
        vs1.setBounds(10, 100, 130, 23);

        vs2.setText("Daal Pakoda");
        jPanel2.add(vs2);
        vs2.setBounds(10, 130, 100, 23);

        vs3.setText("Manchurian");
        jPanel2.add(vs3);
        vs3.setBounds(10, 160, 100, 23);

        vs4.setText("Crispy Babycorn");
        jPanel2.add(vs4);
        vs4.setBounds(10, 190, 130, 23);

        ns1.setText("Chicken Lollipop");
        jPanel2.add(ns1);
        ns1.setBounds(140, 100, 130, 23);

        ns2.setText("Lemon Chicken");
        jPanel2.add(ns2);
        ns2.setBounds(140, 130, 110, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(80, 130, 280, 240);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Dessert");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(100, 10, 160, 30);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(0, 50, 280, 10);

        d2.setText("Brownie");
        jPanel3.add(d2);
        d2.setBounds(30, 110, 130, 23);

        d1.setText("Ice Cream");
        jPanel3.add(d1);
        d1.setBounds(30, 80, 130, 23);

        d3.setText("Gulab Jamun");
        jPanel3.add(d3);
        d3.setBounds(30, 140, 130, 23);

        d4.setText("Jalebi ");
        jPanel3.add(d4);
        d4.setBounds(30, 170, 130, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(790, 140, 280, 240);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Main Course");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(60, 10, 160, 30);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator3);
        jSeparator3.setBounds(0, 50, 280, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Non-Veg");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(170, 60, 80, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Veg");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(50, 70, 40, 20);

        vm1.setText("Paneer Makhani");
        jPanel4.add(vm1);
        vm1.setBounds(20, 100, 120, 23);

        vm2.setText("Daal Fry");
        jPanel4.add(vm2);
        vm2.setBounds(20, 130, 70, 23);

        vm3.setText("Mushroom");
        jPanel4.add(vm3);
        vm3.setBounds(20, 160, 90, 23);

        vm4.setText("Mix Veg");
        jPanel4.add(vm4);
        vm4.setBounds(20, 190, 70, 23);

        nm1.setText("Chicken Handi");
        jPanel4.add(nm1);
        nm1.setBounds(140, 100, 110, 23);

        nm2.setText("Chicken Masala");
        jPanel4.add(nm2);
        nm2.setBounds(140, 130, 120, 23);

        nm3.setText("Fish Fry");
        jPanel4.add(nm3);
        nm3.setBounds(140, 160, 80, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(430, 140, 280, 240);

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(720, 410, 90, 40);

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("Add");
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(430, 410, 90, 40);

        reserve.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reserve.setText("Reserve");
        reserve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveActionPerformed(evt);
            }
        });
        getContentPane().add(reserve);
        reserve.setBounds(570, 410, 90, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABHISHEK\\Desktop\\college docs\\Project\\documents\\Images\\food.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        vs1.setSelected(false);
        vs2.setSelected(false);
        vs3.setSelected(false);
        vs4.setSelected(false);
        ns1.setSelected(false);
        ns2.setSelected(false);
        ns3.setSelected(false);
        vm1.setSelected(false);
        vm2.setSelected(false);
        vm3.setSelected(false);
        vm4.setSelected(false);
        nm1.setSelected(false);
        nm2.setSelected(false);
        nm3.setSelected(false);
        d1.setSelected(false);
        d2.setSelected(false);
        d3.setSelected(false);
        d4.setSelected(false);
        
    }//GEN-LAST:event_resetActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         String pk = Packages.pcombo.getSelectedItem().toString();
    
    if(pk == "Package 1")
    {
        vs1.setSelected(true);
        vs2.setEnabled(false);
        vs3.setEnabled(false);
        vs4.setEnabled(false);
        ns1.setSelected(true);
        ns2.setEnabled(false);
        ns3.setEnabled(false);
        vm1.setSelected(true);
        vm2.setSelected(true);
        vm3.setEnabled(false);
        vm4.setEnabled(false);
        nm1.setSelected(true);
        nm2.setEnabled(false);
        nm3.setEnabled(false);
        d1.setSelected(true);
        d2.setEnabled(false);
        d3.setEnabled(false);
        d4.setEnabled(false);
    }
     
          if(pk == "Package 2")
    {
        vs1.setSelected(true);
        vs2.setSelected(true);
        vs3.setEnabled(false);
        vs4.setEnabled(false);
        ns1.setSelected(true);
        ns2.setEnabled(false);
        ns3.setEnabled(false);
        vm1.setSelected(true);
        vm2.setSelected(true);
        vm3.setSelected(true);
        vm4.setEnabled(false);
        nm1.setSelected(true);
        nm2.setSelected(true);
        nm3.setEnabled(false);
        d1.setSelected(true);
        d2.setSelected(true);
        d3.setEnabled(false);
        d4.setEnabled(false);
    }
     
       if(pk == "Package 3")
    {
        vs1.setSelected(true);
        vs2.setSelected(true);
        vs3.setEnabled(false);
        vs4.setEnabled(false);
        ns1.setSelected(true);
        ns2.setSelected(true);
        ns3.setEnabled(false);
        vm1.setSelected(true);
        vm2.setSelected(true);
        vm3.setSelected(true);
        vm4.setEnabled(false);
        nm1.setSelected(true);
        nm2.setSelected(true);
        nm3.setEnabled(false);
        d1.setSelected(true);
        d2.setSelected(true);
        d3.setSelected(true);
        d4.setEnabled(false);
    }
           if(pk == "Package 4")
    {
        vs1.setSelected(true);
        vs2.setSelected(true);
        vs3.setSelected(true);
        vs4.setEnabled(false);
        ns1.setSelected(true);
        ns2.setSelected(true);
        ns3.setEnabled(false);
        vm1.setSelected(true);
        vm2.setSelected(true);
        vm3.setSelected(true);
        vm4.setEnabled(false);
        nm1.setSelected(true);
        nm2.setSelected(true);
        nm3.setSelected(true);
        d1.setSelected(true);
        d2.setSelected(true);
        d3.setSelected(true);
        d4.setEnabled(false);
    }
           if(pk == "Package 5")
    {
        vs1.setSelected(true);
        vs2.setSelected(true);
        vs3.setSelected(true);
        vs4.setSelected(true);
        ns1.setSelected(true);
        ns2.setSelected(true);
        ns3.setSelected(true);
        vm1.setSelected(true);
        vm2.setSelected(true);
        vm3.setSelected(true);
        vm4.setSelected(true);
        nm1.setSelected(true);
        nm2.setSelected(true);
        nm3.setSelected(true);
        d1.setSelected(true);
        d2.setSelected(true);
        d3.setSelected(true);
        d4.setSelected(true);
    }
         
    }//GEN-LAST:event_addActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        home_page h = new home_page();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_backActionPerformed

    private void reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveActionPerformed
        // TODO add your handling code here:
        
         
      if(vs1.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=123";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      
      if(vs2.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=246";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(vs3.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=176";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(vs4.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=196";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(ns1.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=172";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(ns2.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=276";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(ns3.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=272";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(vm1.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=656";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(vm2.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=356";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(vm3.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=659";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(vm4.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=621";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(nm1.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=279";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(nm2.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=531";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(nm3.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=987";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(d1.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=767";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(d2.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=763";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(d3.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=761";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
      if(d4.isSelected())
      {
        String query="SELECT F_ID,F_NAME,F_TYPE from menu where f_id=769";
        String query1="INSERT INTO SELECTED VALUES(?,?,?)";
        try
        {
            pst=connect.getConnection().prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next())
            {
            int fid=rs.getInt(1);
            String fname=rs.getString(2);
            String ftype=rs.getString(3);
            
            
            pst1=connect.getConnection().prepareStatement(query1);
            pst1.setInt(1,fid);
            pst1.setString(2,fname);
            pst1.setString(3,ftype);
            pst1.execute();
            
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
        }
        
      }
        JOptionPane.showMessageDialog(null,"Cuisine added");
        setVisible(false);
        Reservation rv = new Reservation();
        rv.setVisible(true);
        
    }//GEN-LAST:event_reserveActionPerformed

    private void vs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vs1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_vs1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuisines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuisines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuisines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuisines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuisines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JRadioButton d4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton nm1;
    private javax.swing.JRadioButton nm2;
    private javax.swing.JRadioButton nm3;
    private javax.swing.JRadioButton ns1;
    private javax.swing.JRadioButton ns2;
    private javax.swing.JRadioButton ns3;
    private javax.swing.JButton reserve;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton vm1;
    private javax.swing.JRadioButton vm2;
    private javax.swing.JRadioButton vm3;
    private javax.swing.JRadioButton vm4;
    private javax.swing.JRadioButton vs1;
    private javax.swing.JRadioButton vs2;
    private javax.swing.JRadioButton vs3;
    private javax.swing.JRadioButton vs4;
    // End of variables declaration//GEN-END:variables
}
