/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author ABHISHEK
 */
public class home_page extends javax.swing.JFrame {

    /**
     * Creates new form home_page
     */
    public home_page() {
        initComponents();
    }
     public void close(){
    
    WindowEvent w=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        logout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        payment = new javax.swing.JButton();
        venue = new javax.swing.JButton();
        cuisine = new javax.swing.JButton();
        packages = new javax.swing.JButton();
        reservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1158, 700));
        setPreferredSize(new java.awt.Dimension(1158, 700));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel4.setText("Celebrino");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 10, 190, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Best Caterers in your Town.");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 70, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABHISHEK\\Desktop\\college docs\\Project\\documents\\Images\\home-3.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-40, 0, 1200, 240);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 240);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel3.setText("Services");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 20, 100, 40);

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("We provide catering services for a variety of occasions – from Personal\n Events to Religious & Other Functions,Wedding Related Events to Office \nEvents.\nAre you used to buying food from restaurants and worry about how\n expensive it is? You will be surprised at the effective cost of \ncatering for  \nyour event from a catering service provider. Find prices as low as Rs. 180/- \nper head for a full meal when you order online through \nCelebrino!\nWe offer a wide variety of choices in cuisines from Punjabi and Mughlai\n to all South Indian preparations including Brahmin, Karnataka, \nTamil, Kerala and Andhra Cuisines. In addition, we offer preparation \nstyles from a variety of regional cuisines including Bengali,\nMaharashtrian, Rajasthani, Gujarati and even Continental! ");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 70, 750, 280);

        logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout);
        logout.setBounds(530, 400, 190, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(410, 240, 750, 460);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        payment.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        payment.setText("Payment");
        payment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel3.add(payment);
        payment.setBounds(120, 360, 140, 40);

        venue.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        venue.setText("Venues");
        venue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        venue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venueActionPerformed(evt);
            }
        });
        jPanel3.add(venue);
        venue.setBounds(120, 50, 140, 40);

        cuisine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cuisine.setText("Cuisines");
        cuisine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineActionPerformed(evt);
            }
        });
        jPanel3.add(cuisine);
        cuisine.setBounds(120, 210, 140, 40);

        packages.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        packages.setText("Packages");
        packages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packagesActionPerformed(evt);
            }
        });
        jPanel3.add(packages);
        packages.setBounds(120, 130, 140, 40);

        reservation.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reservation.setText("Reservation");
        reservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationActionPerformed(evt);
            }
        });
        jPanel3.add(reservation);
        reservation.setBounds(110, 280, 160, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 240, 410, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        Payment p = new Payment();
        p.setVisible(true);
        close();
    }//GEN-LAST:event_paymentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Start_page sp = new Start_page();
        sp.setVisible(true);
        close();  
    }//GEN-LAST:event_logoutActionPerformed

    private void venueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venueActionPerformed
        // TODO add your handling code here:
       Venues v =  new Venues();
        v.setVisible(true);
        close();
        
    }//GEN-LAST:event_venueActionPerformed

    private void cuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuisineActionPerformed
        // TODO add your handling code here:
        Cuisines c = new Cuisines();
        c.setVisible(true);
        close();
    }//GEN-LAST:event_cuisineActionPerformed

    private void packagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packagesActionPerformed
        // TODO add your handling code here:
        Packages pp = new Packages();
        pp.setVisible(true);
        close();
    }//GEN-LAST:event_packagesActionPerformed

    private void reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationActionPerformed
        // TODO add your handling code here:
        Reservation r = new Reservation();
        r.setVisible(true);
        close();
    }//GEN-LAST:event_reservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cuisine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton logout;
    private javax.swing.JButton packages;
    private javax.swing.JButton payment;
    private javax.swing.JButton reservation;
    private javax.swing.JButton venue;
    // End of variables declaration//GEN-END:variables
}
