/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.*;
import javax.swing.JOptionPane;
 
public class Payment extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    PreparedStatement ps1;
    ResultSet rs1;
    PreparedStatement ps2;
     PreparedStatement ps3;
    ResultSet rs3;
     Random r = new Random();
    
   
    public Payment() {
        initComponents();
         conn = connect.getConnection();
    }
     public void close(){
    
    WindowEvent w=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mode = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pbkid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pcid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ppeople = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ppk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pvenue = new javax.swing.JTextField();
        show = new javax.swing.JButton();
        back = new javax.swing.JButton();
        pmop = new javax.swing.JComboBox<>();
        abc = new javax.swing.JLabel();
        pphone = new javax.swing.JTextField();
        abc1 = new javax.swing.JLabel();
        pemail = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        ppp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pdate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(865, 514));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 250, 70);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 80, 230, 30);

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Booking ID :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 130, 130, 40);

        pbkid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbkidActionPerformed(evt);
            }
        });
        jPanel2.add(pbkid);
        pbkid.setBounds(220, 130, 190, 30);

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer ID :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 180, 150, 40);

        pcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcidActionPerformed(evt);
            }
        });
        jPanel2.add(pcid);
        pcid.setBounds(220, 180, 190, 30);

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Name :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 230, 190, 40);

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel2.add(pname);
        pname.setBounds(220, 230, 190, 30);

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mode of Payment :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 430, 200, 40);

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Amount :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 380, 150, 40);

        pta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptaActionPerformed(evt);
            }
        });
        jPanel2.add(pta);
        pta.setBounds(220, 380, 190, 30);

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No of People :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(470, 130, 150, 40);

        ppeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppeopleActionPerformed(evt);
            }
        });
        jPanel2.add(ppeople);
        ppeople.setBounds(630, 130, 190, 30);

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Package :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(510, 180, 110, 40);

        ppk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppkActionPerformed(evt);
            }
        });
        jPanel2.add(ppk);
        ppk.setBounds(630, 180, 190, 30);

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Venue :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(530, 280, 90, 40);

        pvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvenueActionPerformed(evt);
            }
        });
        jPanel2.add(pvenue);
        pvenue.setBounds(630, 280, 190, 30);

        show.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        show.setText("Show Details");
        show.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel2.add(show);
        show.setBounds(520, 390, 100, 30);

        back.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(740, 390, 80, 30);

        pmop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pmop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHEQUE", "ONLINE" }));
        jPanel2.add(pmop);
        pmop.setBounds(220, 430, 190, 30);

        abc.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        abc.setForeground(new java.awt.Color(255, 255, 255));
        abc.setText("Phone :");
        jPanel2.add(abc);
        abc.setBounds(130, 280, 90, 40);

        pphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pphoneActionPerformed(evt);
            }
        });
        jPanel2.add(pphone);
        pphone.setBounds(220, 280, 190, 30);

        abc1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        abc1.setForeground(new java.awt.Color(255, 255, 255));
        abc1.setText("Email-ID :");
        abc1.setToolTipText("");
        jPanel2.add(abc1);
        abc1.setBounds(100, 330, 120, 40);

        pemail.setToolTipText("");
        pemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemailActionPerformed(evt);
            }
        });
        jPanel2.add(pemail);
        pemail.setBounds(220, 330, 190, 30);

        confirm.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        confirm.setText("Confirm");
        confirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel2.add(confirm);
        confirm.setBounds(640, 390, 80, 30);

        ppp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pppActionPerformed(evt);
            }
        });
        jPanel2.add(ppp);
        ppp.setBounds(630, 230, 190, 30);

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price/Person :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(470, 230, 160, 40);

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(540, 330, 80, 40);

        pdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdateActionPerformed(evt);
            }
        });
        jPanel2.add(pdate);
        pdate.setBounds(630, 330, 190, 30);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABHISHEK\\Desktop\\college docs\\Project\\documents\\Images\\thong-vo-2482-unsplash.jpg")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-10, 0, 910, 510);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pbkidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbkidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbkidActionPerformed

    private void pcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcidActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void ptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptaActionPerformed

    private void ppeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppeopleActionPerformed

    private void ppkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppkActionPerformed

    private void pvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pvenueActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
         String query="SELECT EMAIL,CUST_ID,CUST_NAME,PHONE FROM CUSTOMER WHERE EMAIL=?";
         String query1="SELECT PK_NAME,PRICE_PER_PERSON FROM PACKAGES WHERE PK_NAME=?";
         String query2="SELECT BOOKING_ID,RES_DATE,NO_OF_PEOPLE FROM RESERVATION WHERE CUST_ID=?";
         String pkg=Packages.pcombo.getSelectedItem().toString();
        try
        {
          ps=connect.getConnection().prepareStatement(query); 
          ps.setString(1,login.lemail.getText());
          rs=ps.executeQuery();
          while(rs.next())
          {
              pemail.setText(rs.getString("EMAIL"));
              pcid.setText(rs.getString("CUST_ID"));
              pname.setText(rs.getString("CUST_NAME"));
              pphone.setText(rs.getString("PHONE"));
              
              
          } 
          ppk.setText(Packages.pcombo.getSelectedItem().toString());
          pvenue.setText(Venues.vcombo.getSelectedItem().toString());
          
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        try
        {
              ps1=connect.getConnection().prepareStatement(query1); 
              ps1.setString(1,pkg);
              rs1=ps1.executeQuery();
              while(rs1.next())
                {
                   ppp.setText(rs1.getString("PRICE_PER_PERSON"));
                }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
         try
        {
          ps3=connect.getConnection().prepareStatement(query2); 
          ps3.setString(1,pcid.getText());
          rs3=ps3.executeQuery();
          while(rs3.next())
          {
              pbkid.setText(rs3.getString("BOOKING_ID"));
              pdate.setText(rs3.getString("RES_DATE")); 
              ppeople.setText(rs3.getString("NO_OF_PEOPLE"));
              
              
          } 
          
          
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        String price=ppp.getText();
        int p = Integer.parseInt(price);
        String nop=ppeople.getText();
        int np=Integer.parseInt(nop);
        int result = p*np;
        pta.setText(Integer.toString(result));
        
        pname.setEnabled(false);
        
    }//GEN-LAST:event_showActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        home_page h = new home_page();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_backActionPerformed

    private void pphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pphoneActionPerformed

    private void pemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemailActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        int pkid=r.nextInt(10000);
        String query2="INSERT INTO PAYMENT VALUES(?,?,?,?,?)";
        try
        {
          ps2=connect.getConnection().prepareStatement(query2); 
          ps2.setInt(1,pkid);
          ps2.setInt(2,Integer.parseInt(pcid.getText()));
          ps2.setInt(3,Integer.parseInt(pbkid.getText()));
          ps2.setInt(4,Integer.parseInt(pta.getText()));
          ps2.setString(5,pmop.getSelectedItem().toString());
          ps2.execute();
          JOptionPane.showMessageDialog(null,"Booking Confirmed!");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void pppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pppActionPerformed

    private void pdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Mode;
    private javax.swing.JLabel abc;
    private javax.swing.JLabel abc1;
    private javax.swing.JButton back;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pbkid;
    private javax.swing.JTextField pcid;
    private javax.swing.JTextField pdate;
    private javax.swing.JTextField pemail;
    private javax.swing.JComboBox<String> pmop;
    private javax.swing.JTextField pname;
    public static javax.swing.JTextField ppeople;
    private javax.swing.JTextField pphone;
    private javax.swing.JTextField ppk;
    private javax.swing.JTextField ppp;
    private javax.swing.JTextField pta;
    private javax.swing.JTextField pvenue;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
