/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.*;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author ABHISHEK
 */
public class Reservation extends javax.swing.JFrame {
    
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    PreparedStatement ps1;
    ResultSet rs1;
     PreparedStatement ps2;
    ResultSet rs2;
     Random r = new Random();
    
    public Reservation() {
        initComponents();
         conn = connect.getConnection();
    }
     public void close(){
    
    WindowEvent w=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        rcust = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rpeople = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rvenue = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        back2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Customer-ID:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 20, 110, 20);
        jPanel1.add(rcust);
        rcust.setBounds(160, 20, 170, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SF_ID", "SF_NAME", "SF_TYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 452, 280);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 230, 530, 410);

        jPanel2.setLayout(null);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(350, 600, 170, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reservation Details :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 190, 240, 30);

        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(100, 90, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("No of People :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 150, 120, 20);
        jPanel3.add(rpeople);
        rpeople.setBounds(170, 140, 80, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Venue :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(80, 30, 70, 20);
        jPanel3.add(rvenue);
        rvenue.setBounds(170, 30, 170, 30);

        jDateChooser1.setDateFormatString("YYYY-MM-DD");
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(170, 80, 170, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(50, 250, 500, 280);

        submit.setBackground(new java.awt.Color(255, 255, 255));
        submit.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        submit.setText("SUBMIT");
        submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit);
        submit.setBounds(110, 600, 170, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ABHISHEK\\Desktop\\college docs\\Project\\documents\\Images\\LVS09qA.jpg")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 740);

        back2.setBackground(new java.awt.Color(255, 255, 255));
        back2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        back2.setText("Back");
        back2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2ActionPerformed(evt);
            }
        });
        jPanel2.add(back2);
        back2.setBounds(360, 590, 170, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(600, 0, 600, 740);

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel6.setText("Customer Details :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 200, 220, 30);

        jLabel7.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel7.setText("Reservation ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 90, 390, 70);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(90, 150, 350, 30);

        show.setText("Show Details");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(240, 670, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        home_page h = new home_page();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         int bkid=r.nextInt(10000);
         String v=rvenue.getText();
         int a=2;
         if(v=="Venue 1")
         {
             a= 1; 
         }
          if(v=="Venue 2")
         {
           a= 2; 
         }
          if(v=="Venue 3")
         {
            a= 3; 
         }
           if(v=="Venue 4")
         {
             a= 4; 
         }
            if(v=="Venue 5")
         {
            a= 5; 
         }
         String np=rpeople.getText();
         int b= Integer.parseInt(np);
         String c=rcust.getText();
         int d= Integer.parseInt(c);
          String query2="INSERT INTO RESERVATION VALUES(?,?,?,?,?)";
        try
        {
          ps=connect.getConnection().prepareStatement(query2); 
          ps.setInt(1,d);
          ps.setInt(2,bkid);
          ps.setString(3,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
          ps.setInt(4,a);
          ps.setInt(5,b);
          ps.execute();
          
          
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        setVisible(false);
        Payment ob=new Payment();
       ob.setVisible(true);
    }//GEN-LAST:event_submitActionPerformed

    private void back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back2ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
         String query="SELECT EMAIL,CUST_ID FROM CUSTOMER WHERE EMAIL=?";
         String query1="SELECT * FROM SELECTED";
        try
        {
          ps=connect.getConnection().prepareStatement(query); 
          ps.setString(1,login.lemail.getText());
          rs=ps.executeQuery();
          while(rs.next())
          {
             
              rcust.setText(rs.getString("CUST_ID"));
              
          } 
          
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       try
       {
           ps1=connect.getConnection().prepareStatement(query1); 
           rs1=ps1.executeQuery();
           jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
           
       }
       catch(SQLException e)
       {
           System.out.println(e);
       }
       
      rvenue.setText(Venues.vcombo.getSelectedItem().toString());
      rvenue.setEnabled(false);
      rcust.setEnabled(false);
      
      
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rcust;
    public static javax.swing.JTextField rpeople;
    private javax.swing.JTextField rvenue;
    private javax.swing.JButton show;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
